### ISSUE TITLE
PTAU ceremony necessary?

### ISSUE THREAD

**Issue by themandalore** [cawfree/zk-starter#1]
Just curious, to actually use this in production, we'd need to go through a whole ceremony to get some true random entries right?  Or can you use an existing ceremony / have that built in?  

(awesome repo btw)

**Comment by cawfree** [comment]
Hey @themandalore, thanks a lot!

During the [`postinstall`](https://github.com/cawfree/zk-starter/blob/main/scripts/postinstall.ts) process (i.e. after our package dependencies have finished installing after a call to `npm i` or `yarn`) we compute a new Powers of Tau ceremony [if the related artifacts aren't found](https://github.com/cawfree/zk-starter/blob/main/scripts/ptau.sh).

These results are autogenerated in the `build/` folder, and are used to compile your arithmetic circuits and the corresponding validation logic.

You can also go through a new ceremony by deleting the `build/` folder and running `yarn`.

**Comment by themandalore** [comment]
thanks!  Was really hoping to just see if you'd need to do the whole "trusted" process / ceremony thing to create one that's actually random / secret or if you use an existing one

**Comment by cawfree** [comment]
Got you. It's hard to say. We do compute some of our own values, but this sequence has been ported directly over from [battlezips](https://github.com/BattleZips/BattleZips/blob/master/scripts/ptau.sh).

It looks like we do compute some of our own values, but [we also rely upon some predefined constants](https://github.com/BattleZips/BattleZips/blob/d83d938fea21e65988d4a547e0a88772c2f387e5/scripts/ptau.sh#L28). We could probably override this with a different source of randomness?
